id: P14B8CCA0
initial_creation_type: input
source_metadata:
  title: Ethical Guidelines
  language: bo
  description: 'The following texts are currently available as part of our Ethical
    Guidelines series:'
  volume:
    29d33954153c4886ad24c549248a4c6c:
      title: A Powerful Pith Instruction to Abstain from Tobacco, the Tenacious Demon
        Plaguing People of Degenerate Times
      parent: Abstention
    22f8d79744a349bbab20a580cf6a15f9:
      title: Song of Advice for Giving Up Meat Eating
      parent: Abstention
    9ccfc3c7ddc043ffa0e621f9f8b91a6f:
      title: The Mirror Clearly Showing What to Adopt and Abandon
      parent: Behavioural Guidelines
    32a074d4ebfd4f33abe8328027cfc8c3:
      title: Drodung Monastery Guidelines
      parent: Behavioural Guidelines
    0c5ddf014f82434699b7b970ecb14548:
      title: 'The Pellucid Mirror: Behavioural Guidelines for the Saṅgha'
      parent: Behavioural Guidelines
    a06e56f91d7441bbb7fe1663b4f05d16:
      title: 'The Seed of Benefit and Happiness: Behavioural Guidelines'
      parent: Behavioural Guidelines
    3d2e9efecb344c59956c692282ec765e:
      title: A Plea to Those who Present ‘Red Offerings’ to Worldly Deities
      parent: Ethical Advice
    5a63208b324243d084f04c3424038dbd:
      title: Nine Considerations and Criteria for Benefiting Beings
      parent: Ethical Advice
created_at: '2022-03-01T03:40:18.761863'
last_modified_at: '2022-03-01T03:40:18.761866'
statistics:
  total_words: 12248
  total_non_words: 1404
quality:
  non_words_ratio: 0.11
